name: Publish Preview

on:
  issue_comment:
    types: created

permissions:
  contents: read
  pull-requests: write

jobs:
  publish-preview:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '@metamaskbot publish-preview') }}
    uses: MetaMask/github-tools/.github/workflows/publish-preview.yml@v1
    with:
      rename-after-install-and-build: true
      environment: default-branch
      build-command: yarn workspace @metamask/stellar-wallet-snap build:prod
      docs-url: 'https://github.com/MetaMask/core/blob/main/docs/processes/preview-builds.md'
    secrets:
      PUBLISH_PREVIEW_NPM_TOKEN: ${{ secrets.PUBLISH_PREVIEW_NPM_TOKEN }}
      BUILD_ENV: |
        {
          "ENVIRONMENT": "production",
          "LOG_LEVEL": "all",
          "RPC_URL_MAINNET": "${{ secrets.RPC_URL_MAINNET }}",
          "HORIZON_URL_MAINNET": "${{ secrets.HORIZON_URL_MAINNET }}",
          "EXPLORER_MAINNET_BASE_URL": "${{ secrets.EXPLORER_MAINNET_BASE_URL }}",
          "RPC_URL_TESTNET": "${{ secrets.RPC_URL_TESTNET }}",
          "HORIZON_URL_TESTNET": "${{ secrets.HORIZON_URL_TESTNET }}",
          "EXPLORER_TESTNET_BASE_URL": "${{ secrets.EXPLORER_TESTNET_BASE_URL }}",
          "TOKEN_API_BASE_URL": "${{ secrets.TOKEN_API_BASE_URL }}",
          "STATIC_API_BASE_URL": "${{ secrets.STATIC_API_BASE_URL }}",
          "PRICE_API_BASE_URL": "${{ secrets.PRICE_API_BASE_URL }}"
        }
